### ISSUE TITLE
Images for readme file

### ISSUE THREAD

**Issue by dhirajdhule** [flytbase/Obstacle_detection__HCSR04#1]
![sonar_jig](https://cloud.githubusercontent.com/assets/10280687/17396651/ff939cdc-5a51-11e6-8a77-9b91d15594bb.JPG)

**Comment by dhirajdhule** [comment]
done

**Comment by dhirajdhule** [comment]
![sonar_webapp](https://cloud.githubusercontent.com/assets/10280687/17398315/c8031880-5a59-11e6-84ae-be1d31a32f2e.png)

**Comment by sharvashish** [comment]
![sonar](https://cloud.githubusercontent.com/assets/13434353/17547419/bfc44860-5f04-11e6-85e6-dbfcd2564dbf.png)

**Comment by sharvashish** [comment]
![sonar](https://cloud.githubusercontent.com/assets/13434353/17568626/33b5a13a-5f62-11e6-8b8e-f7bc1a7326a8.png)
